### ISSUE TITLE
Add a button/link to go to sherlocode

### ISSUE THREAD

**Issue by bbatsov** [art-w/sherlodoc#2]
It'd be nice if there was a quick way to jump to shelocode from sherlodoc. Perhaps just a small button somewhere in the header?

**Comment by EmileTrotignon** [comment]
There is now a button from sherlocode to sherlodoc, but not the opposite.
I am closing this issue as fulfilled, but I opened a new one that asks for the link in the opposite direction.

**Comment by bbatsov** [comment]
Thanks!
