### ISSUE TITLE
StdLib links gives 404

### ISSUE THREAD

**Issue by m-spitfire** [art-w/sherlodoc#6]
Steps:
- Search for `: list list -> list`
- Click on first result: https://ocaml.org/p/ocaml-variants/4.12.0+domains/doc/Stdlib/List/index.html#val-concat
- Got 404

In order to resolve this I think you need to handle `ocaml-variants` as a special case, since it doesn't have any docs on usual page

**Comment by art-w** [comment]
Yes you are right, thanks! We added a special case for the stdlib to point to the official https://v2.ocaml.org/releases/5.1/api/ and updated the stdlib version to the real 5.1 rather than the odd `ocaml-variants` :)

Feel free to reopen this issue if you still encounter any issue!
